### ISSUE TITLE
Eval the BKE without webinteraction

### ISSUE THREAD

**Issue by Fujiaoji** [code-philia/Dynaphish#2]
Hi Ruofan, Hope you doing well. I am wondering that 1) how can I evaluate the BKE + PhishIntention without the webinteraction part? I want the BKE can search online to expand the reference list, is it the code related to the "wi_enabled" ? and 2) how to test on not live websites (like former crawled URL, HTML, and screenshot) without interaction part, directly delete webintetaction part is okay? Thanks.

**Comment by lindsey98** [comment]
Hi Fujiao,
  Yes, it would be ok to delete the webintetaction part.

**Comment by Fujiaoji** [comment]
> Hi Fujiao, Yes, it would be ok to delete the webintetaction part.

Thanks for your reply.
